### ISSUE TITLE
Parm issues in .\Get-CRTReport.ps1

### ISSUE THREAD

**Issue by mignosad** [CrowdStrike/CRT#10]
PS C:\Scripts> .\Get-CRTReport.ps1
At C:\Scripts\Get-CRTReport.ps1:96 char:4
+ 95 Param (
+    ~~~~~
Unexpected token 'Param' in expression or statement.
At C:\Scripts\Get-CRTReport.ps1:97 char:8
+ 96     [Switch]$BasicAuth,
+        ~~~~~~~~~~~~~~~~~~
Unexpected token '[Switch]$BasicAuth' in expression or statement.
At C:\Scripts\Get-CRTReport.ps1:97 char:3
+ 96     [Switch]$BasicAuth,
+   ~
Missing closing ')' in expression.
At C:\Scripts\Get-CRTReport.ps1:102 char:5
+ 101 );
+     ~
Unexpected token ')' in expression or statement.
At C:\Scripts\Get-CRTReport.ps1:111 char:5
+ 108 Function Out-Summary {
+     ~~~~~~~~
Unexpected token 'Function' in expression or statement.
At C:\Scripts\Get-CRTReport.ps1:112 char:9
+ 109     Param
+         ~~~~~
Unexpected token 'Param' in expression or statement.
At C:\Scripts\Get-CRTReport.ps1:113 char:9
+ 110     (
+         ~
Unexpected token '(' in expression or statement.
At C:\Scripts\Get-CRTReport.ps1:114 char:13
+ 111         [string]$string,
+             ~~~~~~~~~~~~~~~
Unexpected token '[string]$string' in expression or statement.
At C:\Scripts\Get-CRTReport.ps1:114 char:4
+ 111         [string]$string,
+    ~
Missing closing ')' in expression.
At C:\Scripts\Get-CRTReport.ps1:114 char:14
+ 111         [string]$string,
+              ~
Array index expression is missing or not valid.
Not all parse errors were reported.  Correct the reported errors and try again.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : UnexpectedToken

**Comment by csdr4** [comment]
@mignosad thanks for the feedback. Can you confirm which version of PowerShell you are using, and whether script execution policy is set to unrestricted when you run this?

**Comment by mignosad** [comment]
Hi Thanks for the replay.  I got this to run by redownloading the script. I must have had a corrupt download the first time.

Thanks
