### ISSUE TITLE
Use the -Encoding option in Export-Csv to avoid garbled characters

### ISSUE THREAD

**Issue by thy-666** [CrowdStrike/CRT#13]
Use -Encoding option in Export-CSV to avoid garbled characters

Export-Csv uses ASCII as the default encoding in PowerShell 5.1, so if we are using multibyte characters, we will get garbled characters. In my environment, I have confirmed that it works correctly by adding "-Encoding Default".

https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/export-csv?view=powershell-5.1

However, this behavior seems to have been changed in PowerShell 6 and later. I tried to check the behavior in PowerShell 7.1, but I did not check the -Encoding behavior because CRT does not work in any place except Export-Csv.

https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/export-csv?view=powershell-7

**Comment by csdr4** [comment]
@thy-666 Can you clarify which encoding you're having trouble with? If you're getting garbled characters with Export-Csv's **_default_** ASCII encoding, how does adding "-Encoding Default" resolve that?

**Comment by thy-666** [comment]
Sorry for the lack of explanation.
I've attached a sample of the code with "-Encoding Default", before and after the change, and Office365AdminGroupMembers_Export.png after the change for files containing multi-byte characters. The meaning of the character string where the cursor is placed is "Global Administrator" in Japanese.

Office365AdminGroupMembers.png is the one before the change, and you can see that the same part is "????" that is garbled.


[Get-CRTReport_Export.txt](https://github.com/CrowdStrike/CRT/files/5767706/Get-CRTReport_Export.txt)
![Office365AdminGroupMembers_Export](https://user-images.githubusercontent.com/48973084/103598787-cf59b580-4f46-11eb-87bc-7b8e13abbb44.png)
![Office365AdminGroupMembers](https://user-images.githubusercontent.com/48973084/103598799-d385d300-4f46-11eb-9cc4-061f7347f365.png)

**Comment by thy-666** [comment]
I created a pull request. pls check it.
https://github.com/CrowdStrike/CRT/pull/16

**Comment by csdr4** [comment]
Thanks @thy-666; I'll will be reviewing your pull request here shortly.

**Comment by csdr4** [comment]
@thy-666 We're making some additional changes all at once, so I am pushing these changes into the next update without explicitly merging your pull request. Thanks for your contribution!
