### ISSUE TITLE
Unnecessarially requires admin rights when missing modules in PSv5

### ISSUE THREAD

**Issue by poshcodebear** [CrowdStrike/CRT#17]
When running without admin rights under PSv5 while missing one or both of the required modules, it complains that you should run as an admin to allow it to install them.  This is unnecessary: they can be installed for just the current user without that by adding `-Scope CurrentUser` to the `Install-Module` command.  PowerShell 7+ (probably 6 as well, but I never really used that version much) already does this by default.

**Comment by csdr4** [comment]
Thanks for the input @poshcodebear; taking a look changing this now. Should be updated in the next commit.
