### ISSUE TITLE
Recommend breaking the script up into separate files

### ISSUE THREAD

**Issue by poshcodebear** [CrowdStrike/CRT#19]
Managing and changing a monolithic script is significantly more cumbersome than one that has been broken into parts.  I recommend at the very least breaking each function into its own file (preferably assembled as a module) and each test/report as a separate script.  This would leave the launch script as the process at a high level making it easy to see the workflow.

**Comment by csdr4** [comment]
Thanks for your suggestion @poshcodebear; with this script specifically we opted to not to take the modular approach to make it as simple as possible for folks to use. While that does make it a little more tricky sometimes to work with, each module/command is broken into a unique "section" inside the script so they can be easily and quickly identified and tweaked as needed.

**Comment by poshcodebear** [comment]
While I disagree with the decision, I do appreciate you taking the time to explain your reasons.
