### ISSUE TITLE
Inaccurate instructions

### ISSUE THREAD

**Issue by DeanGross** [CrowdStrike/CRT#20]
This statement "you must log into the Azure Admin Portal as Global Admin:

https://admin.microsoft.com/AdminPortal/Home#/partners" is not correct, the link does not point to the Azure Admin Portal, it points to the M365 Admin center. 

Please correct the text or the link as appropriate

**Comment by csdr4** [comment]
Great catch @DeanGross; thanks for the feedback. This has been updated.
