### ISSUE TITLE
Can't authenticate to exchange with ADFS?

### ISSUE THREAD

**Issue by whatisthiswebsiteeven** [CrowdStrike/CRT#23]
I cannot authenticate to exchange online using this tool, seems to have something to do with the fact my tenant is utilizing ADFS? Is this a known issue?

**Comment by csdr4** [comment]
@whatisthiswebsiteeven there is an issue noted in the README regarding ADFS authentication. PowerShell is not able to handle multiple connections to Exchange Online + Azure AD in the same PS session. Hoping to writeup a workaround soon.
