### ISSUE TITLE
Permissions Update and AccessRights Values

### ISSUE THREAD

**Issue by funkwhatyouheard** [CrowdStrike/CRT#24]
Was able to confirm that global reader/Exchange admin is all that's required for pulling 'Send As' or 'SendOnBehalf' fields.

Additionally, 'AccessRights' field does not properly output in json or csv. Object type and length returned instead of value:
csv output: "

System.Collections.Generic.List`1[Microsoft.Exchange.Management.AdminApiProvider.RecipientAccessRight]
--

"

json output: "AccessRights":  [
                             1
                         ]

**Comment by funkwhatyouheard** [comment]
Addressed in https://github.com/CrowdStrike/CRT/pull/25

**Comment by csdr4** [comment]
This should be fixed now. I did change the way we're displaying it to be consistent with other modules. Thank you!
