### ISSUE TITLE
Request: Skip testing if login fails

### ISSUE THREAD

**Issue by yellow-starburst** [CrowdStrike/CRT#3]
Separating AzureAD and O365 Enumeration increases testing flexibility.

**Comment by csdr4** [comment]
Thanks for your feedback @yellow-starburst; this is on my list for review/to-do!

**Comment by yellow-starburst** [comment]
Background - Some users may face login failures due to various conditional access controls or incorrect privileges. 
Modified request that may be easier - If authentication fails skip to the next part of testing.

**Comment by csdr4** [comment]
@yellow-starburst indeed. I am also planning to implement better handling for those cases, however, our assumption is that if you are trying to hunt in your environment properly for these configurations, you will obtain the appropriate permissions to pull the data.

**Comment by csdr4** [comment]
Logins for Exchange Online and Azure AD have been separated.
