### ISSUE TITLE
Update release notes and requirements - this only runs on Windows platform!

### ISSUE THREAD

**Issue by trizzosk** [CrowdStrike/CRT#4]
Hi!
thx for great and comprehensive tool - but please - add a note to release notes (readme) that this can only be run on Windows powershell.
I tried to run this on macos Mojave as well as Fedora (all modules in pwsh installed) but still ending with error:

`Import-Module: Could not load file or assembly 'System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified.`

Based on my little search the System.Windows.Forms is not and will not be a part of powershell core. Or - scrpt needs to be completely rewritten for using `Az` instead of `AzureAD`

Thank you.

**Comment by csdr4** [comment]
@trizzosk Great point! I'll add that note to the Readme. Thanks for you feedback!
