### ISSUE TITLE
Required modules will NOT be installed automatically

### ISSUE THREAD

**Issue by ser86** [CrowdStrike/CRT#7]
With the actual line 1
`#Requires -Module ExchangeOnlineManagement,AzureAD`
If you don't have the modules already installed the script's execution fail with the following error
```
.\Get-CRTReport.ps1 : The script 'Get-CRTReport.ps1' cannot be run because the following modules that are specified by the "#requires" statements of the script are missing: ExchangeOnlineManagement.
At line:1 char:1
+ .\Get-CRTReport.ps1
+ ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (Get-CRTReport.ps1:String) [], ScriptRequiresException
    + FullyQualifiedErrorId : ScriptRequiresMissingModules
```
Commenting or removing the first line resolve the issues.

**Comment by csdr4** [comment]
@ser86 thanks for the comment; great catch! I will be implementing better pre-req checks and installation here shortly, but will remove this line for the time being.
