### ISSUE TITLE
SendAsGranted - Miss-type in variable name??

### ISSUE THREAD

**Issue by LarsVonZipper** [CrowdStrike/CRT#9]
Apologies, im new to this.
Is there a miss-type on line 1085:

$DelegatesSendPerms += Get-EXOMailbox -ResultSize Unlimited | Where-Object {$_.GrantSendOnBehalfTo -ne $null}

should it be: '$Delegate...' and NOT '$Delegates...' (there seems to be an extra 's' )

If i've screwed up reporting this, im sorry
Kind regards
Lars

**Comment by csdr4** [comment]
@LarsVonZipper Great catch, thanks for pointing this out. Resolved in next commit.
